Plugin.define do
name "phpSysInfo"
authors [
"Brendan Coles <bcoles@gmail.com>", 

"Andrew Horton", 

]
version "0.4"
description "PHPSysInfo is a customizable PHP Script that parses /proc, and formats information nicely. It will display information about system facts like Uptime, CPU, Memory, PCI devices, SCSI devices, IDE devices, Network adapters, Disk usage, and more."
website "http://phpsysinfo.sourceforge.net/"
matches [
{:ghdb=>'"Created by phpSysInfo"', :certainty=>25},
{:os=>/<td style="width:160px; "><span>Kernel Version<\/span><\/td><td>([^<]+)<\/td><\/tr>/},
{:os=>/<td valign="top"><font size="-1">Distro Name<\/font><\/td>[\r\n\s]*<td><img[^>]+>[\s&nbsp;]*<font size="-1">([^<]+)<\/font><\/td>/},
{:os=>/<td valign="top"><font size="-1">Kernel Version<\/font><\/td>[\r\n\s]*<td><font size="-1">([^<]+)<\/font><\/td>/},
{:text=>'var sTargetURL = "index.php?disp=dynamic";'},
{:url=>"/favicon.ico",:allhash=>"6e0c5b7979e9950125c71341e0960f65"},
{:url=>"/favicon.ico",:allhash=>"a456dd2bae5746beb68814a5ac977048"},
{:url=>"/favicon.ico",:allhash=>"ddcc65196f0bc63a90c885bd88ecbb81"},
{:version=>/<span>Created by <\/span><a href="http:\/\/phpsysinfo.sourceforge.net\/"><span>phpSysInfo - <\/span><span>([^<]+)<\/span>/},
{:version=>/Created by[\s&nbsp;]*<a href="http:\/\/phpsysinfo.sourceforge.net[^>]*>[\s&nbsp;]*phpSysInfo[\s&nbsp;]*-[\s&nbsp;]*([^<]+)<\/a>/},
{:version=>/Generated by[\s&nbsp;]*<a href="http:\/\/phpsysinfo.sourceforge.net[^>]*>[\s&nbsp;]*phpSysInfo[\s&nbsp;]*-[\s&nbsp;]*([^<]+)<\/a>/},
]
end
