Plugin.define do
name "utorrent"
authors [
"Andrew Horton",
]
version "0.1"
description "The uTorrent GUI is a web interface to the uTorrent BitTorrent client"
website "https://web.utorrent.com/"
passive do
m=[]
m<< {:name=>"Page body is 'invalid request'" } if @body == "invalid request"
m<< {:name=>'Basic realm="uTorrent"' } if @headers['www-authenticate'] == 'Basic realm="uTorrent"'
m
end
matches [
{:text=>'<!-- Beta: editnews2.php -->'},
{:text=>'<!-- PrintNews.Bit -->'},
{:text=>'<div class="sf">News generated by <a href="http://www.utopiasoftware.net">Utopia News Pro</a></div>'},
{:text=>'<meta name="generator" content="Utopia News Pro - http://www.utopiasoftware.net/"/>'},
{:version=>/<div align="center" class="fbox smallfont">\s*<!-- Copyright -->\s*Powered By: <a href="about\.php[^"^>]*">Utopia News Pro<\/a> ([^<]+)</},
]
end